quarkus:
  application:
    name: data-enrichment
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  native:
    additional-build-args: -H:ReflectionConfigurationFiles=reflection-config.json
  vertx:
    prefer-native-transport: true

mp:
  messaging:
    incoming:
      gios-measurement:
        connector: smallrye-kafka
        topic: gios.measurement
        key:
          deserializer: pl.airq.common.kafka.TSKeyDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
    outgoing:
      data-enriched:
        connector: smallrye-kafka
        topic: data.enriched
        key:
          serializer: pl.airq.common.kafka.TSKeySerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  group:
    id: airq-data-enrichment
  bootstrap:
    servers: 10.1.1.51:9092

"%dev":
  quarkus:
    http:
      port: 8090
  data-enrichment:
    weather:
      host:
      port: 8096
      ssl: false
  bootstrap:
    servers: localhost:9092
